#ifndef CHEGEL_SHIM_H
#define CHEGEL_SHIM_H

/* The canonical ABI header, generated by cbindgen in hegeldev/hegel-rust
 * (hegel-c/include/hegel.h) and vendored here together with the prebuilt
 * release dylib. See README "Getting libhegel". */
#include "../../Vendor/libhegel/hegel.h"

#endif
